spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pwa_shop
    username: postgres
    password: Den4ikfx123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8080
